name:                backprop-learn
version:             0.1.0.0
github:              mstksg/backprop-learn
license:             BSD3
author:              Justin Le
maintainer:          justin@jle.im
copyright:           (c) Justin Le 2018
tested-with:         GHC >= 8.2

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Combinators and useful tools for ANNs using the backprop library
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: See README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints
- -O0
# - -fprint-explicit-kinds

dependencies:
- backprop >= 0.2.5
- base >=4.7 && <5
- binary
- bytestring
- conduit
- containers
- decidable
- deepseq
- finite-typelits
- foldl >= 1.4
- functor-products
- ghc-typelits-extra
- ghc-typelits-knownnat
- ghc-typelits-natnormalise
- hmatrix
- hmatrix-backprop >= 0.1.2.2
- hmatrix-vector-sized
- list-witnesses
- microlens
- microlens-th
- mwc-random
- one-liner
- one-liner-instances
- opto
- primitive
- profunctors
- singletons
- statistics
- transformers
- typelits-witnesses
- vector >= 0.12.0.2
- vector-sized
- vinyl
- contravariant

library:
  source-dirs: src

_exec: &exec
  source-dirs: app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -O2
  - -Wall

executables:
  backprop-learn-mnist:
    <<: *exec
    main: mnist.hs
    dependencies:
    - backprop-learn
    - data-default
    - filepath
    - mnist-idx
    - time
    - stm
  backprop-learn-series:
    <<: *exec
    main: series.hs
    dependencies:
    - backprop-learn
    - data-default
    - filepath
    - optparse-applicative
    - time
    - singletons
  backprop-learn-char-rnn:
    <<: *exec
    main: char-rnn.hs
    dependencies:
    - backprop-learn
    - data-default
    - time
    - text
  backprop-learn-word2vec:
    <<: *exec
    main: word2vec.hs
    dependencies:
    - backprop-learn
    - data-default
    - time
    - text

